// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "railgorail/avito/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// PrController is an autogenerated mock type for the PrController type
type PrController struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *PrController) Create(ctx context.Context, _a1 *entity.PullRequest) (string, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.PullRequest) (string, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.PullRequest) string); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.PullRequest) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: ctx, prID
func (_m *PrController) GetById(ctx context.Context, prID string) (*entity.PullRequest, error) {
	ret := _m.Called(ctx, prID)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 *entity.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.PullRequest, error)); ok {
		return rf(ctx, prID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.PullRequest); ok {
		r0 = rf(ctx, prID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, prID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkAsMerged provides a mock function with given fields: ctx, prID
func (_m *PrController) MarkAsMerged(ctx context.Context, prID string) error {
	ret := _m.Called(ctx, prID)

	if len(ret) == 0 {
		panic("no return value specified for MarkAsMerged")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, prID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPrController creates a new instance of PrController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPrController(t interface {
	mock.TestingT
	Cleanup(func())
}) *PrController {
	mock := &PrController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
