# Use the official Golang image
FROM golang:1.25.3-alpine

# Set the working directory
WORKDIR /app

# Copy go.mod and go.sum files to leverage Docker cache
COPY go.mod go.sum ./
# Download dependencies
RUN go mod download

# Copy the entire project
COPY . .

# Command to run the e2e tests
# It waits for the test-app to be available and then runs the tests.
CMD ["go", "test", "-v", "./tests/e2e/..."]
