// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "railgorail/avito/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// StatsProvider is an autogenerated mock type for the StatsProvider type
type StatsProvider struct {
	mock.Mock
}

// GetAssignmentsCountStats provides a mock function with given fields: ctx, sort
func (_m *StatsProvider) GetAssignmentsCountStats(ctx context.Context, sort string) ([]*entity.UserStatistics, error) {
	ret := _m.Called(ctx, sort)

	if len(ret) == 0 {
		panic("no return value specified for GetAssignmentsCountStats")
	}

	var r0 []*entity.UserStatistics
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*entity.UserStatistics, error)); ok {
		return rf(ctx, sort)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*entity.UserStatistics); ok {
		r0 = rf(ctx, sort)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.UserStatistics)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sort)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPrStats provides a mock function with given fields: ctx
func (_m *StatsProvider) GetPrStats(ctx context.Context) (*entity.PrStatistics, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetPrStats")
	}

	var r0 *entity.PrStatistics
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*entity.PrStatistics, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *entity.PrStatistics); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.PrStatistics)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewStatsProvider creates a new instance of StatsProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStatsProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *StatsProvider {
	mock := &StatsProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
